### ISSUE TITLE
iOS does not accept objects with null or undefined values

### ISSUE THREAD

**Issue by byudaniel** [couchbaselabs/nativescript-couchbase#30]
Saving documents with null or undefined values saves correctly in Android, but causes iOS to crash.

`db.updateDocument('testId', { test: null })` will cause a crash, `db.updateDocument('testId', { test: '' })` works as expected.

**Comment by nraboy** [comment]
This issue is now corrected in 1.0.11.  I had the fix in the development branch, but just merged it into the master and published to NPM.

Best,

**Comment by byudaniel** [comment]
@nraboy Unfortunately, this does not solve the issue. This patch only fixes `db.updateDocument('testId', null)`, but not when an individual property within the document is `null`. I think it may have to do with how NativeScript is marshalling `null` or `undefined` inside an `NSDictionary`.

**Comment by nraboy** [comment]
@mehfuzh you are the iOS wizard.  Any thoughts?

**Comment by byudaniel** [comment]
Ha, actually have not touched a line of Objective-C. I was just playing around with this and I think it can solve the problem:
`var cleanedData = JSON.parse(JSON.stringify(data));
    for(let prop in cleanedData) {
      if (cleanedData.hasOwnProperty(prop) && cleanedData[prop] === null) {
        cleanedData[prop] = NSNull.null();
      }
 }`

**Comment by byudaniel** [comment]
It will also need to handle nested objects and arrays.

**Comment by byudaniel** [comment]
`{ values: [NSNull.null(), 2, NSNull.null()] }` gets deserialized as `{ values: [{}, 2, {}] }`, I'll need to do more research about the intricacies of [marshalling](https://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview.html).

**Comment by nraboy** [comment]
I'm wondering if there is a better way.  Just to confirm everything works fine on Android correct?  I did the Android stuff and @mehfuzh did the iOS stuff.  I as well don't know any Objective-C.

**Comment by nraboy** [comment]
@tjvantoll,

How does NativeScript marshal null or undefined object values for iOS?

**Comment by tjvantoll** [comment]
@nraboy `null` becomes `NSNull` (see https://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview#primitive-exceptions), and I _believe_ `undefined` does as well.

**Comment by mshanak** [comment]
before inserting or updating the document , use this code to check if any attribute is null and replace it with ""

       
    for (var attribute in document) {
        if (document[attribute] == null)
            document[attribute]="";
    }

**Comment by Eonfuzz** [comment]
I'm running into this issue myself on iOS, has there been any mention of a fix?

**Comment by alonstar** [comment]
+1
